[system]
compatible=PlutoFreeze
bootloader=custom
data-directory=/home/.rauc
bundle-formats=verity

[keyring]
path=/etc/rauc/pluto-prod.cert.pem

[handlers]
bootloader-custom-backend=/usr/bin/pluto_bootloader_backend
# pre-install=/usr/lib/rauc/pre-install.sh
# post-install=/usr/lib/rauc/post-install.sh

[slot.rootfs.0]
bootname=A
device=/dev/disk/by-label/ROOTA
type=raw

[slot.bootfs.0]
device=/dev/disk/by-label/EFIA
parent=rootfs.0
type=raw

[slot.rootfs.1]
bootname=B
device=/dev/disk/by-label/ROOTB
type=raw

[slot.bootfs.1]
device=/dev/disk/by-label/EFIB
parent=rootfs.1
type=raw
