# PlutoOS Temporary pacman.conf file

[options]
HoldPkg = pacman glibc
Architecture = auto
SigLevel = Never
LocalFileSigLevel = Optional
CacheDir = ./pacman-cache
LogFile = ./pacman.log
Color
CheckSpace

# plutoos override repos
[pluto-core]
Server = https://infra.local.77z.dev/pkg/$repo/$arch
SigLevel = Optional TrustAll

# baseline archlinux repos
#
# main mirror:   https://losangeles.mirror.pkgbuild.com/
# backup mirror: https://arch.mirror.constant.com/
#                https://mirrors.kernel.org/archlinux/$repo/os/$arch

[core]
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
SigLevel = Optional TrustAll

[extra]
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
SigLevel = Optional TrustAll
