[system]
compatible=PlutoFreeze
bootloader=custom
data-directory=/mnt/home/.rauc

[keyring]
path=pluto-prod.cert.pem

[handlers]
bootloader-custom-backend=/usr/bin/pluto_bootloader_backend

[slot.bootfs.0]
device=/dev/disk/by-label/EFIA
type=raw
parent=rootfs.0

[slot.rootfs.0]
device=/dev/disk/by-label/ROOTA
type=raw
bootname=A


[slot.bootfs.1]
device=/dev/disk/by-label/EFIB
type=raw
parent=rootfs.1

[slot.rootfs.1]
device=/dev/disk/by-label/ROOTB
type=raw
bootname=B
